jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPERADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Basic\CmsBundle\Entity\Users, property: login}
    encoders :
        Basic\CmsBundle\Entity\Users:
            algorithm : md5
            iterations : 1
            encode_as_base64 : false

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /system/login_check
                login_path: /system/login
                always_use_default_target_path: false
                default_target_path: /
            logout:
                path:   /system/logout
                target: /
#            remember_me:
#              key:      "%secret%"
#              lifetime: 31536000
#              path:     /
#              domain:   ~
    access_denied_url: /system/login
    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN}
